# Generated by Django 5.0.2 on 2024-02-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_question_experience_alter_question_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['experience', 'skill']},
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.file'),
        ),
    ]
