# Generated by Django 5.0.2 on 2024-02-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_question_options_alter_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='repository',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data.repository'),
            preserve_default=False,
        ),
    ]
