# Generated by Django 5.0.2 on 2024-02-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_question_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['experience', 'skill', 'id']},
        ),
    ]
