# Generated by Django 5.0.2 on 2024-02-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['experience', 'skill', '-id']},
        ),
    ]
